version: '2'
services:
    web:
      image: nginx:latest
      container_name: dockercp-desafio05  
      ports:
          - "8080:80"
      volumes:
          - ./index.html:/var/www/html/index.html
          - ./nginx.conf:/etc/nginx/conf.d/default.conf